/* The COFF linker resolves references even in discarded SDL platform entry
 * points. These game-only functions are outside the integration test. Keep
 * them in a separate TU (no shared prototypes); any accidental call aborts.
 * The actual controller, configuration and Controls window code is linked.
 */
#include <stdio.h>
#include <stdlib.h>
#define UNUSED_GAME_FUNCTION(name) \
    void name(void) { fputs("Unexpected game call: " #name "\n", stderr); abort(); }

UNUSED_GAME_FUNCTION(Platform_StartSilentAudio)
UNUSED_GAME_FUNCTION(Monitor_Shared)
UNUSED_GAME_FUNCTION(Menu_LoadSettings)
UNUSED_GAME_FUNCTION(Settings_Get)
UNUSED_GAME_FUNCTION(Monitor_Fact)
UNUSED_GAME_FUNCTION(Log_Printf)
UNUSED_GAME_FUNCTION(GlPicture_Init)
UNUSED_GAME_FUNCTION(Menu_Init)
UNUSED_GAME_FUNCTION(Menu_SetHdPicture)
UNUSED_GAME_FUNCTION(Menu_SetPresentPass)
UNUSED_GAME_FUNCTION(Menu_SetVisible)
UNUSED_GAME_FUNCTION(Menu_AutoScale)
UNUSED_GAME_FUNCTION(Menu_SetScale)
UNUSED_GAME_FUNCTION(Menu_Height)
UNUSED_GAME_FUNCTION(Platform_SetPresentRefresh)
UNUSED_GAME_FUNCTION(Settings_Set)
UNUSED_GAME_FUNCTION(Settings_Save)
UNUSED_GAME_FUNCTION(GlPicture_Replay)
UNUSED_GAME_FUNCTION(GlPicture_Scale)
UNUSED_GAME_FUNCTION(GlPicture_WideTexture)
UNUSED_GAME_FUNCTION(GlPicture_ReadWide)
UNUSED_GAME_FUNCTION(Hud_Signature)
UNUSED_GAME_FUNCTION(SaveIcon_Rgba)
UNUSED_GAME_FUNCTION(GlPicture_Texture)
UNUSED_GAME_FUNCTION(GlPicture_ShownTexture)
UNUSED_GAME_FUNCTION(GlPicture_CopyInto)
UNUSED_GAME_FUNCTION(GlPicture_Lost)
UNUSED_GAME_FUNCTION(GlPicture_Stop)
UNUSED_GAME_FUNCTION(Platform_NotifyPresent)
UNUSED_GAME_FUNCTION(Platform_SetVSync)
UNUSED_GAME_FUNCTION(GlPicture_Read)
UNUSED_GAME_FUNCTION(GlPicture_Behind)
/* The software-controls fixture has no GL core presenter; as on the
 * unsupported backend, report unavailable so SDL can keep its plain path. */
int PresentPass_InitCore(void) { return 0; }
UNUSED_GAME_FUNCTION(ModsWindow_Event)
UNUSED_GAME_FUNCTION(ModsWindow_Redraws)
UNUSED_GAME_FUNCTION(ModsWindow_RequestClose)
UNUSED_GAME_FUNCTION(ModsWindow_Grabs)
UNUSED_GAME_FUNCTION(ModsWindow_Drag)
UNUSED_GAME_FUNCTION(ModsWindow_TextFocus)
UNUSED_GAME_FUNCTION(ModsWindow_Locate)
UNUSED_GAME_FUNCTION(ModsWindow_Tick)
UNUSED_GAME_FUNCTION(Menu_Event)
UNUSED_GAME_FUNCTION(Spu_SetOutputVolume)
UNUSED_GAME_FUNCTION(Spu_Muted)
UNUSED_GAME_FUNCTION(Spu_SetMuted)
UNUSED_GAME_FUNCTION(QuitPrompt_Request)
UNUSED_GAME_FUNCTION(Menu_NoticeShown)
UNUSED_GAME_FUNCTION(Menu_ShowNotice)
UNUSED_GAME_FUNCTION(Menu_NoticePad)
UNUSED_GAME_FUNCTION(HostActions_Run)
UNUSED_GAME_FUNCTION(Platform_StepFrame)
UNUSED_GAME_FUNCTION(Memories_StateRequest)
UNUSED_GAME_FUNCTION(Platform_ScriptedPad2)
UNUSED_GAME_FUNCTION(Log_Drain)
UNUSED_GAME_FUNCTION(Cheats_Frame)
UNUSED_GAME_FUNCTION(Cards_Frame)
UNUSED_GAME_FUNCTION(Duelists_Frame)
UNUSED_GAME_FUNCTION(Platform_ScriptedBits)
UNUSED_GAME_FUNCTION(Platform_ScriptedBits2)
UNUSED_GAME_FUNCTION(Menu_IsOpen)
UNUSED_GAME_FUNCTION(Platform_VSyncPacesGame)
UNUSED_GAME_FUNCTION(Platform_GameHz)
UNUSED_GAME_FUNCTION(Platform_PresentRefresh)
UNUSED_GAME_FUNCTION(Menu_Draw)
UNUSED_GAME_FUNCTION(Hud_Draw)
UNUSED_GAME_FUNCTION(Menu_Bounds)
UNUSED_GAME_FUNCTION(Menu_TakeChanged)
UNUSED_GAME_FUNCTION(Update_Frame)
UNUSED_GAME_FUNCTION(Hud_Bounds)
UNUSED_GAME_FUNCTION(DeckMenu_Active)
UNUSED_GAME_FUNCTION(DeckMenu_Close)
UNUSED_GAME_FUNCTION(DeckMenu_Request)
UNUSED_GAME_FUNCTION(PresentPass_Wanted)
UNUSED_GAME_FUNCTION(PresentPass_Begin)
UNUSED_GAME_FUNCTION(PresentPass_End)
UNUSED_GAME_FUNCTION(FusionHelper_Viewport)
UNUSED_GAME_FUNCTION(Platform_HasDesktopGL)
UNUSED_GAME_FUNCTION(Menu_Open)
UNUSED_GAME_FUNCTION(Menu_SetOverlayArea)
UNUSED_GAME_FUNCTION(TouchPad_Block)
UNUSED_GAME_FUNCTION(TouchPad_Covers)
UNUSED_GAME_FUNCTION(TouchPad_Finger)
UNUSED_GAME_FUNCTION(TouchPad_FreeSpan)
UNUSED_GAME_FUNCTION(TouchPad_Layout)
UNUSED_GAME_FUNCTION(TouchPad_OtherInput)
UNUSED_GAME_FUNCTION(TouchPad_SetMode)
UNUSED_GAME_FUNCTION(TouchPad_Shown)
UNUSED_GAME_FUNCTION(TouchPad_TakeMenu)
UNUSED_GAME_FUNCTION(TouchPad_TakePresses)
UNUSED_GAME_FUNCTION(TouchPad_Update)
UNUSED_GAME_FUNCTION(TouchPadArt_Draw)
