#ifndef MEMORIES_PC_GUEST_IMAGE_H
#define MEMORIES_PC_GUEST_IMAGE_H
/* ILP32 bring-up memory model: the 2 MiB of PS1 RAM is mapped at its real
 * KSEG0 address, so game globals linked at their retail addresses, pointers
 * stored in game data and 32-bit structure layouts all hold unchanged. The
 * same pages are visible at KSEG1 and at the physical address (from 0x10000;
 * hosts reserve the first 64 KiB), which is what 24-bit packet links use.
 * The scratchpad is a page of its own at 0x9F800000, the console's KSEG0
 * view of it, which game C addresses through SCRATCHPAD_ADDR (types.h).
 * The retail view at 0x1F800000 shows the same page where the host lets it
 * be mapped (not in an Android app, whose Java heap is there). Native code
 * never relies on it: every native path that takes a retail address (the
 * MIPS interpreter's accesses and the pointers it hands over, the GPU's
 * address resolver, save states, the control channel) translates it with
 * MEMORIES_SCRATCHPAD_VIEW. Where 0x1F800000 is free but unmappable an
 * access there faults and is redirected (image.c); where something
 * readable holds it, an untranslated access would silently reach that. */
#include <stddef.h>

#include "pc/memory_map.h"
/* The retail scratchpad view's address as the port's (the console's two
 * views of the same RAM); any other address as it is. */
#define MEMORIES_SCRATCHPAD_VIEW(address) \
    ((((address) & 0xfffffc00u) == MEMORIES_GUEST_SCRATCHPAD_RETAIL) ? (address) | 0x80000000u : (address))

/* 1 where 0x1F800000 is mapped as a second view of the scratchpad (Windows;
 * Linux unless something holds the range), 0 where the scratchpad is
 * reached only at 0x9F800000 (an Android app). Set by Memories_GuestMap. */
extern int Memories_ScratchpadRetailView;

/* Both return 0 on success and print the reason on failure. */
int Memories_GuestMap(void);
/* What Memories_GuestMap could not do, in a few words for the player (the
 * Linux and Android one says; "" otherwise). */
const char *Memories_GuestMapError(void);
/* Copy a user-supplied PS-X EXE's initialized image to its load address.
 * MIPS text comes along unused; it keeps every data offset exact. */
int Memories_GuestLoadExe(const char *path);
/* The same, from an executable already in memory (read off the disc image:
 * platform/game_files.h). `name` is for messages. */
int Memories_GuestLoadExeData(const unsigned char *data, size_t size, const char *name);
/* Generated by tools/pc/build_game32.py: every linked function that has a
 * retail address, sorted by that address. */
typedef struct MemoriesGuestFunction {
    unsigned guest;
    void (*host)(void);
    unsigned bank, identifier; /* shared load bank: valid while *bank == identifier; 0 = always */
} MemoriesGuestFunction;
extern const MemoriesGuestFunction Memories_FunctionMap[];
extern const unsigned Memories_FunctionMapCount;

/* Generated likewise: the modules built for a shared load bank, with the host
 * sections holding their variables. See src/pc/guest/modules.c. */
typedef struct MemoriesModule {
    const char *name;
    unsigned bank, identifier;
    char *data, *data_end, *bss, *bss_end;
} MemoriesModule;
extern const MemoriesModule Memories_Modules[];
extern const unsigned Memories_ModuleCount;
#include <stddef.h>
int Memories_ModulesInit(void);
int Memories_ModuleIsResident(unsigned bank, unsigned identifier);
/* Tell the registry that the loader stored into guest memory. */
void Memories_GuestWritten(void *destination, size_t length);

/* Where an indirect call or jump into guest memory goes (branch_thunks.c):
 * the native function of that address, the MIPS interpreter's entry, or the
 * address itself outside guest memory. Set by Memories_GuestMap; while it is
 * NULL every target is taken as it is. */
extern void *(*Memories_GuestBranchResolver)(unsigned address);

/* Reached by a generated stub for a routine with no native implementation. */
void Memories_Unimplemented(const char *name);
#endif
